### ISSUE TITLE
can't be installed

### ISSUE THREAD

**Issue by CLG68** [vtarasv/rai-chem#1]
Hi,

The requirement rdkit-pypi==2022.9.1, can't be resolved by pip.  Pip does not want to install rdkit 2022.9.1.  I can install this version through conda but it still does not want to go through.

I am stuck as rai-chem is needed for pocket-cfdm.

ERROR: Could not find a version that satisfies the requirement rdkit-pypi==2022.9.1 (from rai-chem) (from versions: 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2023.3.1b1)
ERROR: No matching distribution found for rdkit-pypi==2022.9.1

**Comment by vtarasv** [comment]
Hi,

Could you share more details on the OS you are using?

For starters, you may try:
- Update your conda (e.g. `conda update --all`)
- Update your pip (e.g. `pip install --upgrade pip`)
- Check if your python version is >= 3.8

If nothing helps, you could git clone the `rai-chem` repo, edit setup.py so it requires the available rdkit-pypi version (e.g. 2022.9.2), activate the prepared conda environment, and `pip install -e .` in the cloned folder.

Let me know if it helps, please.

**Comment by CLG68** [comment]
Thank you for your help.

I end up importing rai-chem repo locally, edited requirements to rdkit==2022.9.2 and also setup.py.  Then I did: " pip install . " and it seemed to work.

Thank you again,
Christian
